### ISSUE TITLE
allow for expiry of user accounts

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#102]
...and then optional deletion of user accounts past expiry.

Why? Sometimes you create an account to let someone co-edit content. Once that work is done, having the account hanging around just clutters up the site, or, worse, becomes a security vulnerability.

**Comment by tkimnguyen** [comment]
Additional notes:

- Have accounts with built in expiry dates, and default account durations, ability to find expired accounts, or search for accounts about to expire, and setting to indicate if account should be deleted on expiry or left in the site but with no ability to log in
- expiry of an account is optional 
- with (say) a site default of 90 days, or i could manually override the account duration to 30 days. a cron job or something like it would run nightly to check which accounts had gone past their expiry date and would first disable them and move them to a kind of Account Trash Bin 🙂 where they would be really deleted after 30 days (or could just delete the past-expiry accounts immediately, but i think that's less good)
- we have 'lock out' already. we could just set a new date for 'auto lockout'. ... (depends if you want those old locked out accounts hanging around indefinitely though.)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
