### ISSUE TITLE
strict MIME type checking

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#103]
Getting this error when trying to edit a page that the user does have edit permission on (and can click Edit, but then none of the tiles that should be editable are actually accepting the cursor). The user in question is not a Manager but someone in a group that has add/edit/view sharing permissions in the folder. This happens when the user is logged in and when a Manager uses the View As feature and selects to view the site as that user.

I am seeing this with Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Mac. 

The user is going to try another browser.

```Refused to execute script from 'https://site.com/folder/folder2/mainpage//++plone++castle/tinymce-table.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by tkimnguyen** [comment]
User reports that another browser did not have that issue and was able to edit the tiles.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
