### ISSUE TITLE
not compiling on Ubuntu 16.04 due to older version pins

### ISSUE THREAD

**Issue by polyester** [castlecms/castle.cms#104]
installing on Ubuntu 16.04 fails, because of these version-pins in travis.cfg:

- cryptotography = 1.1
- cffi = 1.3.0
- idna = 2.0
- pyOpenSSL = 0.15.1

upgrading these to current versions of the eggs, namely

- cryptography = 2.1.1
- cffi = 1.11.2
- idna = 2.6
- pyOpenSSL = 17.3.0 

makes install work fine, provided the libs (libssl-dev libffi-dev) are there.

Additionally, also in requirements.txt change to cryptography==2.1.1

**Comment by vangheem** [comment]
This was done.
