### ISSUE TITLE
disabling a user should show the change

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#108]
If I disable a user in the users and groups control panel, I should see some kind of status change for that user, e.g. button should go from "disable" to "enable", and maybe the status of the user should be displayed all the time.

![screen shot 2017-11-07 at 1 47 38 pm](https://user-images.githubusercontent.com/815418/32514353-5d975456-c3c2-11e7-920b-c373dcbb7d99.png)

**Comment by tkimnguyen** [comment]
Additional info: the problem occurs if the user has inherited roles from group membership, e.g. Site Administrators group. Once they're removed from that group, we see their status as 'Disabled' and the button 'Enable' appears: 
![screen shot 2017-11-07 at 2 31 36 pm](https://user-images.githubusercontent.com/815418/32516303-72d975aa-c3c8-11e7-9553-3bb3e9d9f782.png)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
