### ISSUE TITLE
display disabled users in Users and Groups control panel

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#109]
Would Be Nice TM to see a list of all disabled users

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
