### ISSUE TITLE
improve "not configured" messages for Content Analytics window

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#121]
"No social data gathered" and "No data could be retrieved. This is likely due because you have not configured Google Analytics API support"

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
