### ISSUE TITLE
Unauthorized: not allowed to access '@@dashboard-utils' 

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#124]
Getting `Unauthorized: You are not allowed to access '@@dashboard-utils' in this context` in the log when I have successfully logged into a site and am automatically taken to the @@dashboard. This goes with the tile's generic error message "We apologize, there was an error rendering this snippet" (see #122) 

This is a curious error since I'm logged in as a Manager.

**Comment by tkimnguyen** [comment]
This happens for regular users too (who are neither Managers nor Site Administrators)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
