### ISSUE TITLE
modify default front page text in a new site

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#128]
...to explain how to use the newly created Castle site, where to get help, etc. (as opposed to the current default front page, which is a copy of the castlecms.io front page, a marketing tool)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
