### ISSUE TITLE
Display issues on mobile

### ISSUE THREAD

**Issue by marcus29200** [castlecms/castle.cms#129]
Tested on Android 7.0 with chrome, and iPhone Safari.

![screenshot_20180115-203809](https://user-images.githubusercontent.com/19508547/34995499-455c6b0e-fa9c-11e7-80fb-672b55a82e78.png)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
