### ISSUE TITLE
content rule that moves items prevents adding them

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#13]
In this example I made a content rule that would move a Comic content type into a /comics folder. Then in the root of the site (ie. not where the rule would move items to) the Add Comic dialog box gives the error "Error validating with server. This should not happen. Contact support" when I click Create and Edit.

![screen shot 2017-02-02 at 11 22 35 pm](https://cloud.githubusercontent.com/assets/815418/22753970/8cc8107a-ee03-11e6-8f18-d12605c94b4c.jpg)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
