### ISSUE TITLE
add EXIF data handling

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#131]
related to #130 

To make exif data searchable for photography library...Castle scrubs all EXIF data. How to allow EXIF data to be allowed for photos going into a photo repository; some visible setting maybe. Also maybe a visual indicator that a given file or image has exif or other metadata, and/or a tile for showing that metadata.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
