### ISSUE TITLE
nonfunctional clickable keywords/categories

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#136]
If you have a keyword tile on a page that has keywords (categories) assigned, clicking on them initially takes you to the correct URL e.g. http://localhost:8081/Castle/@@search?Subject%3Alist=darth but it gets redirected to http://localhost:8081/Castle/@@search?SearchableText=&pageSize=20&page=1 which returns everything on the site.

**Comment by CorySanin** [comment]
Just a little note:
http://localhost:8081/Castle/@@search?Subject=darth currently works as expected. I'm currently trying to add Subject:list as a working parameter.

**Comment by CorySanin** [comment]
#204 fixes it. 👌

**Comment by CorySanin** [comment]
#204 has been merged. gg
