### ISSUE TITLE
Adding files to a folderish object

### ISSUE THREAD

**Issue by zombified** [castlecms/castle.cms#141]
Say I have a path like:

    mysite.com/A/B

and I navigate to B, then click Add and Upload, then upload the file and save. The file goes into the file-repository instead of being saved under the `/A/B/` path, but when you "select upload location" it defaults to the current path (IE `/A/B`).

The way this operates may be intentional, but it seems confusing from a UI/UX perspective -- it would seem that either the default upload location should be the current path or the default value for selecting the file upload location should be the file repository.

Does this makes sense? Thoughts?

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
