### ISSUE TITLE
include a layout that shows lead image

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#15]
If a content type has lead image behaviour enabled (e.g. a News Item) and you set a lead image, it would be nice to see it when you are looking at the item (works in Plone 5)

**Comment by vangheem** [comment]
All basic layouts should include lead image tiles.

**Comment by tkimnguyen** [comment]
To clarify, I mean that if a news item has a lead image set, you should be able to see that lead image when you're looking at the news item. In other words, we should enhance the news item default view so that it checks if there is a lead image set and if so shows it.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
