### ISSUE TITLE
Double Encoding

### ISSUE THREAD

**Issue by djakes** [castlecms/castle.cms#158]
When using "&"  in a summary description, it shows up as "&amp;" on the site. 

![screenshot 1](https://user-images.githubusercontent.com/39918765/40929131-7b6bf966-67e9-11e8-88ab-5b2bb380a5a3.png)
![doubleencoding](https://user-images.githubusercontent.com/39918765/40929133-7b7dbb6a-67e9-11e8-97df-b75cbc9a9a49.png)
![screen 2](https://user-images.githubusercontent.com/39918765/40929134-7b9138d4-67e9-11e8-82e4-948bf7e105ec.png)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
