### ISSUE TITLE
fields added to Dexterity content types do not show up

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#16]
...in the edit or view layouts by default. For example, using the Dexterity types panel I cloned Page / Document CT to make Comic, then I added an Image field. When I add a Comic, I do not see that Image field at all. I understand now that what we see is a function of the layout, so in fact the way I did it worked in Plone but not in Castle; in Castle there is no need to add the image to the CT; instead I'd add the image tile to the layout and save the layout globally (to reuse it). Need to think of a way to integrate layout & Dexterity CT UIs.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
