### ISSUE TITLE
broken image links in the Content Rules control panel

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#17]
when a rule is enabled there is a missing image for it in the "enabled" column: <img class="icon-contentrule-enabled-unassigned" src="https://site.com/++theme++castle.theme/error_icon.png" alt="unassigned" title="this rule has not been assigned" width="16" height="16">

![screen shot 2017-02-08 at 2 14 15 pm](https://cloud.githubusercontent.com/assets/815418/22755486/f8f6c5ca-ee08-11e6-9a64-d45cefe64d90.jpg)

**Comment by RobZoneNet** [comment]
fixed this in actions.xml
