### ISSUE TITLE
make more obvious how to add next/previous in a folder

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#18]
related to https://github.com/castlecms/castle.cms/issues/14 

In Castle, the way to enable next/previous navigation in a folder starts off similar to that in Plone 5: you edit the folder, you go to its Properties, and check the "Enable next previous navigation" box. But then you also have to add a "next/previous" fragment tile to each item in that folder. That should really be part of the setting at the folder level (somehow).

**Comment by vangheem** [comment]
You just add the tile to a slot on the folder

**Comment by vangheem** [comment]
not sure how to make this anymore obvious. Maybe make it it's own tile and not a fragment?

**Comment by tkimnguyen** [comment]
Ah right that is conceptually more sensible (add tile to slot on folder). What happens if folders always have that tile in the footer slot, so that if someone enables next/previous on the folder the tile is ready to go?

**Comment by vangheem** [comment]
Right now, we're using the next/previous tile. If it's added to a folder and inherited properly on childs, it'll work as expected.
