### ISSUE TITLE
Accessibility:  Invalid ARIA attribute value in Video Title

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#20]
Ensures all ARIA attributes have valid values

wcag2a
wcag131
wcag411
wcag412

Target:#mep_1 > .mejs-inner > .mejs-controls > .mejs-time-rail > .mejs-time-total.mejs-time-slider

HTML:
<span class="mejs-time-total mejs-time-slider" style="width: 423px;" aria-label="Time Slider" aria-valuemin="0" aria-valuemax="NaN" aria-valuenow="0" aria-valuetext="00:00" role="slider" tabindex="0">
Summary:

Fix any of the following:
Invalid ARIA attribute value: aria-valuemax="NaN"

**Comment by RobZoneNet** [comment]
Just making a note here: It does aria-valuemax="NaN" on the initial load of the page for IE 10, 11, edge and also chrome. Safari and Firefox don't have the aria stuff until the video is playing.  

Once the video is playing IE 10 keeps the value Nan.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
