### ISSUE TITLE
Secure login view breaking

### ISSUE THREAD

**Issue by obct537** [castlecms/castle.cms#201]
While logging in with two factor enabled, I'm getting a view template error:
`2018-09-10 20:05:22 ERROR Zope.SiteErrorLog 1536609922.970.638547358464 http://10.0.2.2:8080/@@secure-login
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module castle.cms.browser.login, line 58, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module cb6ca5564a3be8b358be930775598864.py, line 508, in render
  Module five.pt.expressions, line 161, in __call__
  Module castle.cms.browser.login, line 385, in options
  Module plone.protect.authenticator, line 95, in createToken
SystemError: error return without exception set

 - Expression: "${view/options}"
 - Filename:   ... /castle.cms/castle/cms/browser/templates/secure-login.pt
 - Location:   (line 35: col 43)
 - Source:     ... cure-login" data-options="${view/options}">
                                             ^^^^^^^^^^^^^^^
 - Arguments:  site_login: False
               repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fd8f0659090>
               views: <ViewMapper - at 0x7fd8db504f10>
               modules: <instance - at 0x7fd8f106e6c8>
               utils: <Utils castle-utils at 0x7fd8db2da410>
               args: <tuple - at 0x7fd8fb672050>
               here: <ImplicitAcquisitionWrapper Zope at 0x7fd8e3ea6910>
               user: <ImplicitAcquisitionWrapper - at 0x7fd8e3ea92d0>
               nothing: <NoneType - at 0x7b1070>
               bad_domain: False
               backend_urls: <list - at 0x7fd8db63dcf8>
               container: <ImplicitAcquisitionWrapper Zope at 0x7fd8e3ea6910>
               request: <instance - at 0x7fd8e0689d40>
               wrapped_repeat: <SafeMapping - at 0x7fd8e21df578>
               portal_url: http://10.0.2.2:8080
               options: {...} (0)
               traverse_subpath: <list - at 0x7fd8db3d1a70>
               default: <object - at 0x7fd8fb648c10>
               only_allow_login_to_backend_urls: False
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Zope at 0x7fd8e3ea6910>
               view: <SimpleViewClass from /opt/plone/src/castle.cms/castle/cms/browser/templates/secure-login.pt secure-login at 0x7fd8db504710>
               translate: <function translate at 0x7fd8e056fa28>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fd8e3ea6910>
               portreg: {...} (2)
               target_language: <NoneType - at 0x7b1070>`

This only happens *after* submitting the login attempt, and the login session is actually created, but the login page only shows and error and doesn't redirect

**Comment by CorySanin** [comment]
Attempted login from /Castle/@@secure-login with 2FA enabled and successfully redirected to dashboard. Chrome and Firefox both work. Using email for authentication. I can't seem to reproduce this.

**Comment by obct537** [comment]
As I reread this, realize I forgot to mention that this is happening when I'm trying to log into the zope root (aka like at localhost:8080/manage). That might make a difference?

**Comment by CorySanin** [comment]
Tried that too, just in case. That also redirects as it should, though it redirects back to the root index instead of the user dashboard.

**Comment by CorySanin** [comment]
Probably forgot to perform upgrade step- probably not an issue 👌
