### ISSUE TITLE
Feature Tile Not Mobile Friendly

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#27]
The Feature Tile does not display properly when there is more than one column.

if you are viewing the page in a mobile device and click on a feature tile (more than one column in the row) the blue div displays after the last tile on the row not after the tile you click on
![desktop](https://cloud.githubusercontent.com/assets/3406360/23713334/985e9282-03f3-11e7-8396-af8c16c3110b.png)
![mobile](https://cloud.githubusercontent.com/assets/3406360/23713333/985db27c-03f3-11e7-83d3-f44564f1a57b.png)

**Comment by vangheem** [comment]
@RobZoneNet I assigned you here. Let me know if it's a js related issue...

**Comment by RobZoneNet** [comment]
Fixed
