### ISSUE TITLE
improve filtering of search results when setting lead image

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#30]
A content item's lead image can be set from another content item's lead image (!) [needs to be documented!]. But when you are searching for an image to use as a lead image, the search results should show 

- all images (obviously)
- only content items that have lead images already set (currently shows content items that may or may not already have lead images)

**Comment by vangheem** [comment]
Well, I'm wrong.

Right now, it only allows selecting images and the base query provided for searching content doesn't seem to be working.
