### ISSUE TITLE
Accessibility Issues in @@secure-login Page

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#327]
**Describe the bug**
For HTML pages add a TITLE element.
- WCAG 2.0 A 2.4.2 
- Section 508 (2017) A 2.4.2 

Use the LANG attribute to identify the language of the page.
In HTML add a LANG attribute to the HTML tag.
- WCAG 2.0 A 3.1.1 
- Section 508 (2017) A 3.1.1

IMG elements must have an ALT attribute.
Add an ALT attribute describing each image, which screen readers read aloud. 
- WCAG 2.0 A F65 
- Section 508 (2017) A F65

**Comment by RobZoneNet** [comment]
These are fixed.
