### ISSUE TITLE
Figure out documentation situation...

### ISSUE THREAD

**Issue by vangheem** [castlecms/castle.cms#33]
Right now, we have one massive README.

Should we go with readthedocs for dev docs?

Or, put dev oriented docs with our user docs?

\cc @tkimnguyen

**Comment by tkimnguyen** [comment]
I prefer to leave docs in the docs folder and make clear that some are user docs and some are dev docs, and not use readthedocs (if that answers your question)

**Comment by tkimnguyen** [comment]
Do you want me to add a new top level folder "docs", and two subfolders "user" and "dev", and slim down the README?

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
