### ISSUE TITLE
Quality Check not checking Event Content

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#4]
The "Links" and "Headers" Quality Check is not working on event types

**Comment by tkimnguyen** [comment]
For Links, do you mean there are correct links but the linked items are not published?

**Comment by rnunez80** [comment]
yes

**Comment by tkimnguyen** [comment]
I confirm seeing an issue with H3 before H2 not flagging the headers check...

**Comment by tkimnguyen** [comment]
I confirm the check isn't flagging a link to a private image

**Comment by vangheem** [comment]
Looks like the celery async process wasn't restarted with last update so it wasn't running the latest code.

Once updated, link integrity objects are populating correctly. See test-page for example working.
