### ISSUE TITLE
be able to have nested navigation

### ISSUE THREAD

**Issue by vangheem** [castlecms/castle.cms#45]
select depth like old plone

**Comment by obct537** [comment]
https://github.com/castlecms/castle.cms/tree/navtile

**Comment by tkimnguyen** [comment]
@RobZoneNet assigning to you to design/theme and then please reassign back to @obct537

**Comment by RobZoneNet** [comment]
![screen shot 2017-06-02 at 5 22 12 pm](https://cloud.githubusercontent.com/assets/103745/26745416/66b58e80-47b8-11e7-8bac-1d52a3bb92d7.png) put in a few styles

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
