### ISSUE TITLE
Celery Error on CastleCMS Status

### ISSUE THREAD

**Issue by sm2x** [castlecms/castle.cms#493]
CastleCMS v.2.6.31
Ubuntu 18.04
I am having Celery: ERROR: Broadcast not supported by transport u'sqla'

![image](https://user-images.githubusercontent.com/6595333/115939026-3e93ef00-a4cf-11eb-8e29-3417ac703698.png)

**Comment by zombified** [comment]
The status check for Celery relies on features not supported by the SQLAlchemy/SQLite broker (defined by the "sqla+sqlite://" part in the BROKER_URL setting)  -- you'll have to setup a broker that supports the Celery 'status' command in order to see a working status check for Celery.
