### ISSUE TITLE
Can't Add fields to EasyForm

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#5]
No way to add fields on EasyForm Content Type

**Comment by tkimnguyen** [comment]
A workaround: try appending /@@fields to the form URL

**Comment by vangheem** [comment]
That test server is using https://github.com/quintagroup/collective.easyform not the updated https://github.com/collective/collective.easyform

Looking at https://github.com/collective/collective.easyform/blob/master/src/collective/easyform/profiles/default/actions.xml it has the Fields menu item but https://github.com/quintagroup/collective.easyform/blob/master/collective/easyform/profiles/default/actions.xml does not.

Going to close as this should work once we update.
