### ISSUE TITLE
option to change default handling of uploads

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#63]
Related to #29 - how much work would it be to have a setting to toggle the default behaviour of the upload handling between:

- repository (currently the default)
- the current folder

so that if this setting "Default uploading to current folder" was checked there would still be a link in the upload dialog to let the user upload to the image/file/video repository ("Upload to repository" where the link "Specify upload location" is currently). 

![screen shot 2017-04-21 at 6 58 09 pm](https://cloud.githubusercontent.com/assets/815418/25288272/16d01778-26c5-11e7-8b37-aab984cb85b9.jpg)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
