### ISSUE TITLE
should be a way to set the default layout for a custom content type

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#66]
...so that when you create an item of that content type you aren't required to choose between that one custom layout and the shipped "basic layout".

![screen shot 2017-04-28 at apr 28 10 19 54 am](https://cloud.githubusercontent.com/assets/815418/25545394/4b80cab2-2c24-11e7-9b0d-f91cb9b8223b.jpg)
![screen shot 2017-04-28 at apr 28 10 20 02 am](https://cloud.githubusercontent.com/assets/815418/25545405/58a4dd78-2c24-11e7-843e-719de8c68b37.jpg)

**Comment by vangheem** [comment]
you can select default layout in the manage layout control panel I believe.

**Comment by obct537** [comment]
@vangheem where is this control panel? Not seeing anywhere you can set a default

**Comment by vangheem** [comment]
`mosaic layout editor`: although, it looks like there is no UI to select one as the default. You'd need to add it to the manifest(which is editable TTW at least).

**Comment by tkimnguyen** [comment]
It's at /@@layouts-editor#autotoc-item-autotoc-2

I even tried to hide the Basic layout but it still shows up

![screen shot 2017-04-28 at apr 28 11 45 02 pm](https://cloud.githubusercontent.com/assets/815418/25552951/ca4983dc-2c6c-11e7-8cad-7c278bcd05a6.jpg)

**Comment by tkimnguyen** [comment]
```[contentlayout]
title = Comic Layout
file = comic-layout.html
for = comic
```
Guess I will dig through code to see what to add to the manifest...

**Comment by tkimnguyen** [comment]
Maybe change the layout title to "Default"...? https://github.com/castlecms/castle.cms/blob/cb8296e7a1c3daf0be46341a6e779868b6d34694/castle/cms/layouts/manifest.cfg#L22

**Comment by tkimnguyen** [comment]
Ah no :( ... would have been too easy :) 

![screen shot 2017-04-28 at apr 28 11 51 22 pm](https://cloud.githubusercontent.com/assets/815418/25552994/9e19cba4-2c6d-11e7-913f-87ad299f12eb.jpg)

**Comment by vangheem** [comment]
https://github.com/castlecms/castle.cms/blob/master/castle/cms/layouts/manifest.cfg

`for = TypeName`

**Comment by tkimnguyen** [comment]
Cripes, it's case sensitive :) Thanks! 

@RobZoneNet some CSS is bleeding over into the site in question... it's transforming the editing area of this layout control panel so all text appears uppercase

**Comment by tkimnguyen** [comment]
leaving this open until I've documented it
