### ISSUE TITLE
problem w/ Chrome on Windows 10 clicking on folders in folder content view

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#67]
While in folder contents view, unable to click on a folder (but able to reorder it). 

Current Chrome version.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
