### ISSUE TITLE
rich text tiles added to dashboard disappear

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#68]
Log in, go to /@@dashboard, click "Edit dashboard"

I try to add a rich text tile to my dashboard. After I place the tile and press Save it seems to disappear but if I go back to Edit, it's there.

**Comment by obct537** [comment]
Notes to self:

The dashboard layout_view redirects the request to /@@dashboard instead of /dashboards/person
Unfortunately the tile is stored directly on /dashboards/person, so when plone.app.tiles lookes for the text, it's not there.

**Comment by obct537** [comment]
Also, this will affect any IPersistentTile, not just raw text

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
