### ISSUE TITLE
problem when closing layout selection and layout management dialogs

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#69]
if hit cancel ("x") on both these dialogs I am left not seeing the expected edit view and have to reload the page

to replicate, add a content type for which you've specified at least one custom layout, press Create and Edit, either dismiss the Select Layout dialog ("x") or click "Manage custom layouts" then dismiss it.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
