### ISSUE TITLE
missing settings in site creation forms/dialogs

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#72]
in the API Settings tab, we are missing several settings from @@castle-settings#autotoc-item-autotoc-1 e.g. the Etherpad settings... is that on purpose?

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
