### ISSUE TITLE
Image enhancement for social media 

### ISSUE THREAD

**Issue by RobZoneNet** [castlecms/castle.cms#74]
Currently we grab the logo for the website which is fine for some customers. Some want the ability to use the lead image instead. So we should make it so that there is a choice setting between leadimage or site icon for when someone like facebook grabs open graph image(og:image)
![metadata](https://cloud.githubusercontent.com/assets/103745/26082899/6254868c-39a0-11e7-874a-3e97a915c859.JPG)
 metatag

http://ogp.me/#types

**Comment by RobZoneNet** [comment]
Also if the customer picks leadImage, then the code would search for a leadImage if not, fall back to the site logo.

**Comment by RobZoneNet** [comment]
I want to update this ticket as it kinda works the way we want if you follow a certain procedure. 
While editing an item, if you click on "properties"
**Doesn't work:** If you  "select image from site to use as the lead image" and it gets the image from the image-repository folder

**Does work:** If you "drop here to replace image or select an image from the hard drive. Only one problem. The url returns something like http://FOO.com/BLAH/BLAH/@@download/image/MYIMAGENAME.jpg. (All caps get replaced obviously).  I think the "@@download" part is causing a small issue with facebook. It has to reindex the site twice.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
