### ISSUE TITLE
fix slot selection dialog

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#75]
left and right slots erroneously appear above and below the content
![screen shot 2017-05-16 at 2 51 53 pm](https://cloud.githubusercontent.com/assets/815418/26125307/52b7be86-3a47-11e7-94d9-018021899a05.jpg)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
