### ISSUE TITLE
Recurrence widget doesn't work.

### ISSUE THREAD

**Issue by obct537** [castlecms/castle.cms#76]
The jquery.recurrencewidget js doesn't work anymore (probably never did). According to the collective.recurrencewidget github, the js isn't made to work with the current version of jQuery (1.11.x). 

React retrofit?

**Comment by obct537** [comment]
Apparently it does work in certain circumstances?

**Comment by tkimnguyen** [comment]
When I click on the Add button in the Recurrence part of the edit view, I see the dialog appears but it is partially hidden. Playing with the inspector I see that div.riform needs its z-index bumped (e.g. to 2000) then it shows correctly.
![screen shot 2017-05-30 at 1 50 44 pm](https://cloud.githubusercontent.com/assets/815418/26599811/89aeab4a-453f-11e7-9e51-89780222488b.jpg)
![screen shot 2017-05-30 at 1 54 11 pm](https://cloud.githubusercontent.com/assets/815418/26599814/8b77a59e-453f-11e7-957b-dd0c064af4b0.jpg)

**Comment by tkimnguyen** [comment]
This may be theme-specific

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
