### ISSUE TITLE
split content-totals div out of dashboard Welcome fragment

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#82]
...and style it for cases in which there are many content types

https://github.com/castlecms/castle.cms/blob/cb8296e7a1c3daf0be46341a6e779868b6d34694/castle/cms/fragments/templates/dashboard-welcome.pt#L100

![screen shot 2017-06-08 at 2 28 07 pm](https://user-images.githubusercontent.com/815418/26947715-4a433edc-4c59-11e7-82b1-c0a577067661.jpg)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
