### ISSUE TITLE
enable live search in navbar-form searchbox

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#83]
live search works on the usual @@search page but not here

![screen shot 2017-06-08 at 2 49 59 pm](https://user-images.githubusercontent.com/815418/26947853-cee26488-4c59-11e7-9c7b-54f1dcf97415.jpg)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
