### ISSUE TITLE
folder contents Creator shows cryptic IDs

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#89]
Click on Manage Content in left toolbar (folder contents view), click on Configure Displayed Columns icon, add Creator column. 

The IDs shown in the Creator column should be human-readable, not these cryptic UID ones:

![](https://chat.wildcardcorp.com/file-upload/G6AEHxhbchGy7nesM/Screen%20Shot%202017-08-24%20at%2011.23.26%20AM.png)

**Comment by tkimnguyen** [comment]
As in the above screen shot, this does not happen with the 'admin' user but it does happen with a user you add via the Site Setup -> Users and Groups panel.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
