### ISSUE TITLE
Castle Toolbar Accessibility: Ensures that lists are structured correctly

### ISSUE THREAD

**Issue by rnunez80** [castlecms/castle.cms#9]
wcag2a
wcag131

**Target:**
#edit-bar > .castle-toolbar-container > .castle-toolbar-container-side > ul

**HTML:**
`<ul data-reactid=".0.1.0">`

**Summary:**
_Fix all of the following:_
List element has direct children that are not allowed inside `<li>` elements

_Related Nodes:_
#edit-bar > .castle-toolbar-container > .castle-toolbar-container-side > ul > span

**Comment by RobZoneNet** [comment]
This is fixed.
