### ISSUE TITLE
browser push notifications

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#91]
Would allow notifying web site visitors or logged in users of various events e.g. new news items, new events, items need review.

- [ ] Safari: https://developer.apple.com/notifications/safari-push-notifications/
- [ ] Chrome: https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/
- [ ] Edge / IE ?
- [ ] Linux / Mac / Windows / iOS / Android support
- [ ] implement "display browser notification" as a new content rule action

![safari notifications](https://user-images.githubusercontent.com/815418/29736891-237fcdec-89cb-11e7-9d03-80783e8c6371.png)

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
