### ISSUE TITLE
content listing tile error

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#97]
When I tried to create a content listing tile I got a very opaque error message if I tried to specify a criterion "Type". "There was an error submitting the form."
There is no error if I do not have a Type criterion.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
