### ISSUE TITLE
Map tile should inform user about Location metadata

### ISSUE THREAD

**Issue by lucid-0** [castlecms/castle.cms#99]
Items and Center Point must be objects which have Location metadata set, if there is no metadata the user's search will return nothing and are not informed how to handle this.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
